int producto(char productos[][30], int tiempo[5]);
int tiempot(int demanda, int tiempo[5], int op);
void caso(int tiempot,int t,int s);
void recu(int op, int demanda[5],int *recurso, int *recursos2, int *recursos3t, int *recursos4t );
int menu(int opc);
void resta(int *recurso, int *recursos2, int *recursos3t, int *recursos4t,int *r1,int *r2,int *r3,int *r4);
void comprobar(int *recurso, int *recursos2, int *recursos3t, int *recursos4t,int *r1,int *r2,int *r3,int *r4,int *n);
void cambio(char productos[][30], int demanda[], int tiempo[]);
void agregar(int op,int cantidad,int *recursos, int *recursos2, int *recursos3, int *recursos4 );
void eliminar(char productos[][30], int demanda[5], int tiempo[5]);
int menu2(int opc);
int ingresor(int *recursos, int *recursos2, int *recursos3, int *recursos4,char productos[][30]);
int demanda( int demanda[5]);
int tiempocliente(int tiempoc, int *t, int *s);
